[[main]]
  name = "About"
  url = "/about/"
  weight = 1

[[main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[main]]
  name = "Docs"
  url = "/docs/"
  weight = 3

[[main]]
  name = "Authors"
  url = "/author/"
  weight = 4